spring:
  datasource:
    username: salas
    password: password
    url: jdbc:postgresql://localhost:5432/kafka-db-integrate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: email-notification-service
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id: salas-test-group
      properties:
        spring:
          json:
            trusted:
              packages: "com.salas.common"
      auto-offset-reset: earliest
server:
  port: 8081
